import Link from "next/link";
import BackButton from "@/components/BackButton";
import { Logo } from "@/components/Brand";
import type { Metadata } from "next";
import { requireAuth } from "@/lib/auth";
import { getInvoiceForUser } from "@/services/invoice.service";
import { formatDate, formatTime, taka } from "@/lib/format";
import { StatusBadge } from "@/components/ui";
import PrintButton from "@/components/PrintButton";

export const metadata: Metadata = { title: "Invoice" };
export const dynamic = "force-dynamic";

export default async function InvoiceDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const user = await requireAuth();
  const invoice = await getInvoiceForUser(id, user.id, user.role);
  const { booking } = invoice;

  const lines = [
    ["Service charge", invoice.subtotal],
    ["HomeEase service fee", invoice.serviceFee],
    ["Urgency fee", invoice.urgencyFee],
    ["Distance fee", invoice.distanceFee],
    ["Discount", -invoice.discount],
  ] as const;

  return (
    <>
      <div className="row-between no-print" style={{ marginBottom: 16 }}>
        <BackButton fallback="/invoices" label="Back" />
        <PrintButton />
      </div>

      <div className="invoice" style={{ maxWidth: 720, margin: "0 auto" }}>
        <div className="row-between" style={{ marginBottom: 22 }}>
          <div>
            <Logo href={null} height={34} />
            <p className="tiny muted">Smart home service automation</p>
          </div>
          <div style={{ textAlign: "right" }}>
            <div className="strong mono">{invoice.invoiceNumber}</div>
            <div className="tiny muted">Issued {formatDate(invoice.issuedAt)}</div>
            <div style={{ marginTop: 6 }}><StatusBadge status={invoice.paymentStatus} /></div>
          </div>
        </div>

        <div className="grid grid-2" style={{ marginBottom: 20 }}>
          <div>
            <div className="stat-label">Billed to</div>
            <div className="strong">{booking.customer.name}</div>
            <div className="small muted">{booking.customer.email}</div>
            <div className="small muted">{booking.customer.phone}</div>
            <div className="small muted">{booking.request.address}</div>
          </div>
          <div>
            <div className="stat-label">Service provider</div>
            <div className="strong">{booking.provider.businessName}</div>
            <div className="small muted">{booking.provider.user.name}</div>
            <div className="small muted">{booking.provider.user.phone}</div>
          </div>
        </div>

        <div style={{ marginBottom: 16 }}>
          <div className="stat-label">Service</div>
          <div className="strong">{booking.request.service.name}</div>
          <div className="small muted">
            {formatDate(booking.scheduledDate)} · {formatTime(booking.startTime)}–{formatTime(booking.endTime)} · {booking.request.area}
          </div>
        </div>

        <table className="invoice-table">
          <tbody>
            {lines.map(([label, amount]) =>
              amount === 0 ? null : (
                <tr key={label}>
                  <td className="small">{label}</td>
                  <td className="mono" style={{ textAlign: "right" }}>{taka(amount)}</td>
                </tr>
              ),
            )}
            <tr className="invoice-total">
              <td>Total</td>
              <td className="mono" style={{ textAlign: "right" }}>{taka(invoice.total)}</td>
            </tr>
          </tbody>
        </table>

        <p className="tiny muted" style={{ marginTop: 20 }}>
          Payment is settled directly with the provider. This invoice is the record of the agreed amount.
          Generated by HomeEase on {formatDate(invoice.issuedAt)}.
        </p>
      </div>
    </>
  );
}
